import type { Event } from './pages/EventsPage/types';
import { Role, Section, type Member, type Scout } from './types';

export const initialScouts: Scout[] = [
  {
    id: '1',
    scoutId: 'ESC001',
    name: 'Harry Potter',
    section: Section.ALCATEIA_JANGAL,
    attendance: 95,
    isPresent: true,
  },
  {
    id: '2',
    scoutId: 'ESC002',
    name: 'Hermione Granger',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 88,
    isPresent: true,
  },
  {
    id: '3',
    scoutId: 'ESC003',
    name: 'Luke Skywalker',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 78,
    isPresent: false,
  },
  {
    id: '4',
    scoutId: 'ESC004',
    name: 'Leia Organa',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 92,
    isPresent: true,
  },
  {
    id: '5',
    scoutId: 'ESC005',
    name: 'Frodo Baggins',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 85,
    isPresent: false,
  },
  {
    id: '6',
    scoutId: 'ESC006',
    name: 'Bilbo Baggins',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 90,
    isPresent: true,
  },

  {
    id: '7',
    scoutId: 'ESC007',
    name: 'Aragorn Elessar',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 98,
    isPresent: true,
  },
  {
    id: '8',
    scoutId: 'ESC008',
    name: 'Gandalf the Grey',
    section: Section.ALCATEIA_JANGAL,
    attendance: 82,
    isPresent: false,
  },
  {
    id: '9',
    scoutId: 'ESC009',
    name: 'Kratos Atreus',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 75,
    isPresent: true,
  },
  {
    id: '10',
    scoutId: 'ESC010',
    name: 'Lara Croft',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 91,
    isPresent: true,
  },
  {
    id: '11',
    scoutId: 'ESC011',
    name: 'Ezio Auditore da Firenze',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 84,
    isPresent: false,
  },
  {
    id: '12',
    scoutId: 'ESC012',
    name: 'Clark Kent',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 79,
    isPresent: true,
  },

  {
    id: '13',
    scoutId: 'ESC013',
    name: 'Bruce Wayne',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 70,
    isPresent: true,
  },
  {
    id: '14',
    scoutId: 'ESC014',
    name: 'Diana Prince',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 93,
    isPresent: true,
  },
  {
    id: '15',
    scoutId: 'ESC015',
    name: 'Peter Parker',
    section: Section.ALCATEIA_JANGAL,
    attendance: 89,
    isPresent: true,
  },
  {
    id: '16',
    scoutId: 'ESC016',
    name: 'Tony Stark',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 96,
    isPresent: false,
  },
  {
    id: '17',
    scoutId: 'ESC017',
    name: 'Steve Rogers',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 81,
    isPresent: true,
  },
  {
    id: '18',
    scoutId: 'ESC018',
    name: 'Sherlock Holmes',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 83,
    isPresent: true,
  },

  {
    id: '19',
    scoutId: 'ESC019',
    name: 'Dr. John Watson',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 77,
    isPresent: false,
  },
  {
    id: '20',
    scoutId: 'ESC020',
    name: 'Katniss Everdeen',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 90,
    isPresent: true,
  },
  {
    id: '21',
    scoutId: 'ESC021',
    name: 'James Bond',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 86,
    isPresent: false,
  },
  {
    id: '22',
    scoutId: 'ESC022',
    name: 'Indiana Jones',
    section: Section.ALCATEIA_JANGAL,
    attendance: 74,
    isPresent: true,
  },
  {
    id: '23',
    scoutId: 'ESC023',
    name: 'Ellen Ripley',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 94,
    isPresent: true,
  },
  {
    id: '24',
    scoutId: 'ESC024',
    name: 'Agent 47',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 71,
    isPresent: false,
  },

  {
    id: '25',
    scoutId: 'ESC025',
    name: 'Solid Snake',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 68,
    isPresent: true,
  },
  {
    id: '26',
    scoutId: 'ESC026',
    name: 'Cloud Strife',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 97,
    isPresent: true,
  },
  {
    id: '27',
    scoutId: 'ESC027',
    name: 'Adrian Fahrenheit Tepes',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 80,
    isPresent: false,
  },
  {
    id: '28',
    scoutId: 'ESC028',
    name: 'Ellie Williams',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 87,
    isPresent: true,
  },
  {
    id: '29',
    scoutId: 'ESC029',
    name: 'Joel Miller',
    section: Section.ALCATEIA_JANGAL,
    attendance: 76,
    isPresent: true,
  },
  {
    id: '30',
    scoutId: 'ESC030',
    name: 'Geralt of Rivia',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 99,
    isPresent: true,
  },

  {
    id: '31',
    scoutId: 'ESC031',
    name: 'Master Chief Petty Officer John-117',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 65,
    isPresent: false,
  },
  {
    id: '32',
    scoutId: 'ESC032',
    name: 'Hercule Poirot',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 73,
    isPresent: true,
  },
  {
    id: '33',
    scoutId: 'ESC033',
    name: 'Miss Marple',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 88,
    isPresent: true,
  },
  {
    id: '34',
    scoutId: 'ESC034',
    name: 'Link Link',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 92,
    isPresent: true,
  },
  {
    id: '35',
    scoutId: 'ESC035',
    name: 'Princess Zelda',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 85,
    isPresent: false,
  },
  {
    id: '36',
    scoutId: 'ESC036',
    name: 'Darth Vader',
    section: Section.ALCATEIA_JANGAL,
    attendance: 60,
    isPresent: true,
  },

  {
    id: '37',
    scoutId: 'ESC037',
    name: 'Jon Snow',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 70,
    isPresent: false,
  },
  {
    id: '38',
    scoutId: 'ESC038',
    name: 'Daenerys Targaryen',
    section: Section.ALCATEIA_LOBO_GUARA,
    attendance: 90,
    isPresent: true,
  },
  {
    id: '39',
    scoutId: 'ESC039',
    name: 'Lord Voldemort',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 66,
    isPresent: false,
  },
  {
    id: '40',
    scoutId: 'ESC040',
    name: 'Arthur Fleck',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 77,
    isPresent: true,
  },
];

export const recentAttendance: Scout[] = [
  {
    id: '4',
    scoutId: 'ESC004',
    name: 'Leia Organa',
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    attendance: 92,
    isPresent: true,
  },
  {
    id: '2',
    scoutId: 'ESC002',
    name: 'Hermione Granger',
    section: Section.ALCATEIA_FLOR_VERMELHA,
    attendance: 88,
    isPresent: true,
  },
  {
    id: '12',
    scoutId: 'ESC012',
    name: 'Clark Kent',
    section: Section.TROPA_ESCOTEIRA_FENIX,
    attendance: 79,
    isPresent: false,
  },
  {
    id: '20',
    scoutId: 'ESC020',
    name: 'Katniss Everdeen',
    section: Section.TROPA_SENIOR_KAINGANG,
    attendance: 90,
    isPresent: true,
  },
  {
    id: '21',
    scoutId: 'ESC021',
    name: 'James Bond',
    section: Section.CLA_PIONEIRO_AGNIRAM,
    attendance: 86,
    isPresent: false,
  },
];

export const mockAttendanceData = {
  scouts: [
    {
      id: '4',
      scoutId: 'ESC004',
      name: 'Leia Organa',
      section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
      attendance: 92,
      isPresent: true,
    },
    {
      id: '2',
      scoutId: 'ESC002',
      name: 'Hermione Granger',
      section: Section.ALCATEIA_FLOR_VERMELHA,
      attendance: 88,
      isPresent: true,
    },
    {
      id: '12',
      scoutId: 'ESC012',
      name: 'Clark Kent',
      section: Section.TROPA_ESCOTEIRA_FENIX,
      attendance: 79,
      isPresent: false,
    },
    {
      id: '20',
      scoutId: 'ESC020',
      name: 'Katniss Everdeen',
      section: Section.TROPA_SENIOR_KAINGANG,
      attendance: 90,
      isPresent: true,
    },
  ],
  leaders: [
    {
      id: 'L01',
      name: 'Albus Dumbledore',
      role: Role.CHEFE_SECAO,
      isPresent: true,
    },
    {
      id: 'L02',
      name: 'Obi-Wan Kenobi',
      role: Role.CHEFE_SECAO,
      isPresent: true,
    },
    {
      id: 'L03',
      name: 'Minerva McGonagall',
      role: Role.MONITOR,
      isPresent: false,
    },
  ],
};

export const initialUpcomingEvents: Event[] = [
  {
    id: '1',
    name: 'Reunião Semanal',
    date: '2025-12-03',
    time: '14:00',
    location: 'Sede do Grupo',
    description: 'Reunião regular de atividades',
    status: 'ongoing',
  },
  {
    id: '2',
    name: 'Acampamento Regional',
    date: '2025-12-15',
    time: '08:00',
    location: 'Parque Municipal',
    description: 'Acampamento de integração regional',
    status: 'scheduled',
  },
  {
    id: '3',
    name: 'Caminhada Ecológica',
    date: '2025-12-20',
    time: '07:00',
    location: 'Trilha do Vale',
    description: 'Atividade de conservação ambiental',
    status: 'scheduled',
  },
];

export const initialPastEvents: Event[] = [
  {
    id: '4',
    name: 'Cerimônia de Abertura',
    date: '2025-11-28',
    time: '18:00',
    location: 'Sede do Grupo',
    status: 'completed',
    attendees: 42,
  },
  {
    id: '5',
    name: 'Mutirão de Limpeza',
    date: '2025-11-20',
    time: '09:00',
    location: 'Praça Central',
    status: 'completed',
    attendees: 38,
  },
];

export const initialMembers: Member[] = [
  {
    id: 'L01',
    name: 'Albus Dumbledore',
    role: Role.CHEFE_SECAO,
    isPresent: true,
    section: Section.ALCATEIA_JANGAL,
    email: 'dumbledore@grupo.com',
    password: '483920',
  },
  {
    id: 'L02',
    name: 'Obi-Wan Kenobi',
    role: Role.CHEFE_SECAO,
    isPresent: true,
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    email: 'obiwan@grupo.com',
    password: '174205',
  },
  {
    id: 'L03',
    name: 'Minerva McGonagall',
    role: Role.MONITOR,
    isPresent: false,
    section: Section.ALCATEIA_FLOR_VERMELHA,
    email: 'mcgonagall@grupo.com',
    password: '905312',
  },
  {
    id: 'L04',
    name: 'Morpheus',
    role: Role.MONITOR,
    isPresent: true,
    section: Section.CLA_PIONEIRO_AGNIRAM,
    email: 'morpheus@grupo.com',
    password: '672410',
  },
  {
    id: 'L05',
    name: 'Professor Xavier',
    role: Role.CHEFE_SECAO,
    isPresent: true,
    section: Section.TROPA_SENIOR_KAINGANG,
    email: 'xavier@grupo.com',
    password: '118734',
  },
  {
    id: 'L06',
    name: 'Captain Kirk',
    role: Role.MONITOR,
    isPresent: false,
    section: Section.ALCATEIA_LOBO_GUARA,
    email: 'kirk@grupo.com',
    password: '550291',
  },
  {
    id: 'L07',
    name: 'Mufasa',
    role: Role.MONITOR,
    isPresent: true,
    section: Section.TROPA_ESCOTEIRA_FENIX,
    email: 'mufasa@grupo.com',
    password: '402876',
  },
  {
    id: 'L08',
    name: 'Mary Poppins',
    role: Role.CHEFE_SECAO,
    isPresent: true,
    section: Section.ALCATEIA_JANGAL,
    email: 'poppins@grupo.com',
    password: '739154',
  },
  {
    id: 'L09',
    name: 'Yoda',
    role: Role.MASTER,
    isPresent: false,
    section: Section.CLA_PIONEIRO_AGNIRAM,
    email: 'yoda@grupo.com',
    password: '222987',
  },
  {
    id: 'L10',
    name: 'Alfred Pennyworth',
    role: Role.MONITOR,
    isPresent: true,
    section: Section.TROPA_ESCOTEIRA_ESCORPIAO,
    email: 'alfred@grupo.com',
    password: '960544',
  },
];

export const mockAuthUsers: Member[] = [
  {
    id: 'L09',
    name: 'Yoda',
    role: Role.MASTER,
    section: Section.CLA_PIONEIRO_AGNIRAM,
    email: 'yoda@grupo.com',
    password: '222987',
  },
  {
    id: 'L01',
    name: 'Albus Dumbledore',
    role: Role.CHEFE_SECAO,
    section: Section.ALCATEIA_JANGAL,
    email: 'dumbledore@grupo.com',
    password: '483920',
  },
  {
    id: 'L03',
    name: 'Minerva McGonagall',
    role: Role.MONITOR,
    section: Section.ALCATEIA_FLOR_VERMELHA,
    email: 'mcgonagall@grupo.com',
    password: '905312',
  },
];
